name: Twelve Data SQL Build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          # Strong password is mandatory for SQL 2022 to start
          MSSQL_SA_PASSWORD: QuantPass_2026! 
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Wait for SQL Server
        # This checks the port from outside the container
        run: |
          echo "Waiting for SQL Server to boot..."
          until nc -z localhost 1433; do
            echo "Port 1433 not ready yet..."
            sleep 5
          done
          echo "Port 1433 is open! Giving SQL 15 more seconds to finish internal setup..."
          sleep 15

      - name: Create Database
        run: |
          docker exec ${{ job.services.sqlserver.id }} /opt/mssql-tools18/bin/sqlcmd \
          -S localhost -U sa -P QuantPass_2026! -C \
          -Q "CREATE DATABASE quantdb"

      - name: Build and Run
        env:
          # Match these to your application.properties and the DB we just created
          SPRING_DATASOURCE_URL: jdbc:sqlserver://localhost:1433;databaseName=quantdb;encrypt=true;trustServerCertificate=true
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: QuantPass_2026!
          TWELVE_DATA_KEY: ${9b30cb5823944374a3668af9d868e162}
        run: |
          mvn clean package -DskipTests
          java -jar target/quanttest.jar

      - name: Upload Txt Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stock-data
          path: api_results.txt
